// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;

namespace Cidco.Middleware.Domain
{
    public partial class CidcoMiddlewareDBContext
    {
        private ICidcoMiddlewareDBProcedures _procedures;

        public virtual ICidcoMiddlewareDBProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new CidcoMiddlewareDBProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public ICidcoMiddlewareDBProcedures GetProcedures()
        {
            return Procedures;
        }
    }

    public partial class CidcoMiddlewareDBProcedures : ICidcoMiddlewareDBProcedures
    {
        private readonly CidcoMiddlewareDBContext _context;

        public CidcoMiddlewareDBProcedures(CidcoMiddlewareDBContext context)
        {
            _context = context;
        }

        public virtual async Task<int> sp_InsertAapleUserAsync(string trackid, string userid, string UsertypeName, string UserName, string Password, string PasswordChanged, string EmailID, string Mobileno, string Fullname, string Fullname_mr, string Occupation, string Age, string gender, string DOB, string UIDNO, string PANNo, string pincode, string Divisionid, string Districtid, string Talukaid, string Villageid, string RegistrationType, string DistrictPrefix, string ServiceID, string UsrTimeStamp, string UsrSession, string ClientCheckSumValue, string strServiceCookie, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "trackid",
                    Size = 100,
                    Value = trackid ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "userid",
                    Size = 100,
                    Value = userid ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "UsertypeName",
                    Size = 50,
                    Value = UsertypeName ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                new SqlParameter
                {
                    ParameterName = "UserName",
                    Size = 1000,
                    Value = UserName ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "Password",
                    Size = 1000,
                    Value = Password ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "PasswordChanged",
                    Size = 100,
                    Value = PasswordChanged ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "EmailID",
                    Size = 200,
                    Value = EmailID ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "Mobileno",
                    Size = 100,
                    Value = Mobileno ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "Fullname",
                    Size = 1000,
                    Value = Fullname ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "Fullname_mr",
                    Size = 1000,
                    Value = Fullname_mr ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "Occupation",
                    Size = 100,
                    Value = Occupation ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "Age",
                    Size = 100,
                    Value = Age ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "gender",
                    Size = 100,
                    Value = gender ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "DOB",
                    Size = 100,
                    Value = DOB ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "UIDNO",
                    Size = 100,
                    Value = UIDNO ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "PANNo",
                    Size = 100,
                    Value = PANNo ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "pincode",
                    Size = 100,
                    Value = pincode ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "Divisionid",
                    Size = 100,
                    Value = Divisionid ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "Districtid",
                    Size = 50,
                    Value = Districtid ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                new SqlParameter
                {
                    ParameterName = "Talukaid",
                    Size = 50,
                    Value = Talukaid ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                new SqlParameter
                {
                    ParameterName = "Villageid",
                    Size = 50,
                    Value = Villageid ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                new SqlParameter
                {
                    ParameterName = "RegistrationType",
                    Size = 100,
                    Value = RegistrationType ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "DistrictPrefix",
                    Size = 100,
                    Value = DistrictPrefix ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "ServiceID",
                    Size = 100,
                    Value = ServiceID ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "UsrTimeStamp",
                    Size = -1,
                    Value = UsrTimeStamp ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "UsrSession",
                    Size = 100,
                    Value = UsrSession ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "ClientCheckSumValue",
                    Size = -1,
                    Value = ClientCheckSumValue ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "strServiceCookie",
                    Size = -1,
                    Value = strServiceCookie ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                parameterreturnValue,
            };
            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [dbo].[sp_InsertAapleUser] @trackid = @trackid, @userid = @userid, @UsertypeName = @UsertypeName, @UserName = @UserName, @Password = @Password, @PasswordChanged = @PasswordChanged, @EmailID = @EmailID, @Mobileno = @Mobileno, @Fullname = @Fullname, @Fullname_mr = @Fullname_mr, @Occupation = @Occupation, @Age = @Age, @gender = @gender, @DOB = @DOB, @UIDNO = @UIDNO, @PANNo = @PANNo, @pincode = @pincode, @Divisionid = @Divisionid, @Districtid = @Districtid, @Talukaid = @Talukaid, @Villageid = @Villageid, @RegistrationType = @RegistrationType, @DistrictPrefix = @DistrictPrefix, @ServiceID = @ServiceID, @UsrTimeStamp = @UsrTimeStamp, @UsrSession = @UsrSession, @ClientCheckSumValue = @ClientCheckSumValue, @strServiceCookie = @strServiceCookie", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<int> sp_InsertEnquiryAsync(string appname, string mobileno, string email, string address, string module, string services, string comm, string mode, string enterby, decimal? Regcharge, string modeofpayment, bool? ispaymentdone, string appno, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "appname",
                    Size = 50,
                    Value = appname ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                new SqlParameter
                {
                    ParameterName = "mobileno",
                    Size = 50,
                    Value = mobileno ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                new SqlParameter
                {
                    ParameterName = "email",
                    Size = 200,
                    Value = email ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                new SqlParameter
                {
                    ParameterName = "address",
                    Size = -1,
                    Value = address ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                new SqlParameter
                {
                    ParameterName = "module",
                    Size = 100,
                    Value = module ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                new SqlParameter
                {
                    ParameterName = "services",
                    Size = 100,
                    Value = services ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                new SqlParameter
                {
                    ParameterName = "comm",
                    Size = -1,
                    Value = comm ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                new SqlParameter
                {
                    ParameterName = "mode",
                    Size = 50,
                    Value = mode ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                new SqlParameter
                {
                    ParameterName = "enterby",
                    Size = 50,
                    Value = enterby ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                new SqlParameter
                {
                    ParameterName = "Regcharge",
                    Precision = 10,
                    Value = Regcharge ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Decimal,
                },
                new SqlParameter
                {
                    ParameterName = "modeofpayment",
                    Size = 50,
                    Value = modeofpayment ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                new SqlParameter
                {
                    ParameterName = "ispaymentdone",
                    Value = ispaymentdone ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Bit,
                },
                new SqlParameter
                {
                    ParameterName = "appno",
                    Size = 50,
                    Value = appno ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                parameterreturnValue,
            };
            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [dbo].[sp_InsertEnquiry] @appname = @appname, @mobileno = @mobileno, @email = @email, @address = @address, @module = @module, @services = @services, @comm = @comm, @mode = @mode, @enterby = @enterby, @Regcharge = @Regcharge, @modeofpayment = @modeofpayment, @ispaymentdone = @ispaymentdone, @appno = @appno", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }
    }
}
