// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
namespace Cidco.Middleware.Domain.Entities;

public class LogInformation
{
    public int LogId { get; set; }

    public int RequestId { get; set; }

    public int ResponseId { get; set; }

    public int AppId { get; set; }

    public string Source { get; set; }

    public string VenderName { get; set; }

    public string Request { get; set; }

    public string Response { get; set; }

    public string UserEmail { get; set; }

    public string ErrorInfo { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string ModifiedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }
}