// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
namespace Cidco.Middleware.Domain.Entities;

public partial class Service
{
    public long Tid { get; set; }

    public string ServiceModule { get; set; }

    public string ServiceHead { get; set; }

    public string Daystaken { get; set; }

    public string LinkedUrl { get; set; }
}