// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
namespace Cidco.Middleware.Domain.Entities;

public partial class StatusTb
{
    public int StatusId { get; set; }

    public string StatusDesc { get; set; }
}