// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
namespace Cidco.Middleware.Domain.Entities;

public partial class VwDailyScrollReport
{
    public long Tid { get; set; }

    public string ApplicationUid { get; set; }

    public string Applicantname { get; set; }

    public string Mobileno { get; set; }

    public string Emailid { get; set; }

    public string Appaddress { get; set; }

    public string Servicemodule { get; set; }

    public string Services { get; set; }

    public string Comments { get; set; }

    public string Entrymode { get; set; }

    public DateTime? Entrydate { get; set; }

    public string Enterby { get; set; }

    public decimal? Registrationcharge { get; set; }

    public string ModeofPayment { get; set; }

    public bool? PaymentDone { get; set; }

    public string Cfccenter { get; set; }

    public string ModuleAppNo { get; set; }

    public DateOnly? AppDate { get; set; }

    public string Apptime { get; set; }
}